// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8EXrkbbE64IDoxi2fwMjtFI9Cu2ywbBE',
    appId: '1:454867203615:web:5ca0a42a3a5234d5eec72a',
    messagingSenderId: '454867203615',
    projectId: 'to-do-list-1cf64',
    authDomain: 'to-do-list-1cf64.firebaseapp.com',
    storageBucket: 'to-do-list-1cf64.firebasestorage.app',
    measurementId: 'G-C8TBRCR3ER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMkphnguMneGUtXSDpN_zC5rCxwRpNHDs',
    appId: '1:454867203615:android:90fe9e6ca4c4e315eec72a',
    messagingSenderId: '454867203615',
    projectId: 'to-do-list-1cf64',
    storageBucket: 'to-do-list-1cf64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAff4vT86o0X9-O46VuY6Vg27qmtxl8oj0',
    appId: '1:454867203615:ios:791ef16e8c1be150eec72a',
    messagingSenderId: '454867203615',
    projectId: 'to-do-list-1cf64',
    storageBucket: 'to-do-list-1cf64.firebasestorage.app',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAff4vT86o0X9-O46VuY6Vg27qmtxl8oj0',
    appId: '1:454867203615:ios:791ef16e8c1be150eec72a',
    messagingSenderId: '454867203615',
    projectId: 'to-do-list-1cf64',
    storageBucket: 'to-do-list-1cf64.firebasestorage.app',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8EXrkbbE64IDoxi2fwMjtFI9Cu2ywbBE',
    appId: '1:454867203615:web:1db6043b58ab7addeec72a',
    messagingSenderId: '454867203615',
    projectId: 'to-do-list-1cf64',
    authDomain: 'to-do-list-1cf64.firebaseapp.com',
    storageBucket: 'to-do-list-1cf64.firebasestorage.app',
    measurementId: 'G-CRENC0MZEN',
  );
}
